version: "3"

services:
  nodejs2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs2
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kcpm_nodejs2
